### ISSUE TITLE
[unknown version] Error mounting url <smb>

### ISSUE THREAD

**Issue by marklajer** [jssimporter/JSSImporter#131]
Hello guys,

After playing around a couple of days trying to figure out what the problem is i hope you guys can help me figure it out.

I get the following error:

AutoPkg
Error mounting url "smb://JSSUSER:JSSPASS@ourjss:445/mountpoint": None
<img width="635" alt="screen-shot-2018-04-24-at-11 18 16" src="https://user-images.githubusercontent.com/4114961/39178298-a1b16d70-47b1-11e8-83c1-90467fcf15ef.png">'

AutoPkgr
<img width="461" alt="screen shot 2018-04-24 at 11 24 42" src="https://user-images.githubusercontent.com/4114961/39178757-cb89d514-47b2-11e8-9e19-8ab9502614b4.png">

I doesn't have any $ in the share name or something like that. If I take the exactly same share (smb://JSSUSER:JSSPASS@ourjss:445/mountpoint) in the error message and put it to the finder I can mount it with out any problems.

Any suggestions?

**Comment by sheagcraig** [comment]
I would take a look at your password and make sure it doesn't have any reserved characters that are going to get escaped by python-jss in this case. For testing purposes, you could certainly create an additional user with a simple abc123 password to see if that's the case..

**Comment by jaakkopoyry** [comment]
I have a similar issue and will examine my password as well. Is there a list of common reserved characters to avoid, or does jss-importer have it's own list of ones to avoid?

**Comment by jaakkopoyry** [comment]
ok, i have narrowed this down. 
My pwd did have special characters so I escaped the offending ones out. Still failed. Those same R/W account credentials wouldn't even work in Finder (10.13.4), so i gave up and went a different route.
1) Removed all DPs from JSSImporter, uninstalled, reinstalled. 
2) Set up my DPs as custom SMB entries rather than rely on JSSImporter to pull them in from Casper.
3) Ensured no mounted DPs were present.
4) ran "autopkg run Firefox.jss.recipe -v".
5) output claimed it failed but about 5 seconds after the autopkg run finished up, lo and behold, my DP mounted successfully on the desktop.

Is the delay in the DP mounting causing my whole issue? Is there any way to put a 'wait' in along the way?

**Comment by jaakkopoyry** [comment]
also, I am not using $ in the share name and the firefox.jss recipe does create the pkg file successfully. Only on connection to the DP does it fail & not deliver the resulting pkg. Re-Running the firefox.jss recipe with the DP mounted still produces a "None " failure and no firefox pkg on the DP.

**Comment by grahampugh** [comment]
It does sound like your DP connection is too slow. Have you tried using HTTPS? Also, this issue is over a year old - did you solve it or move on?

**Comment by grahampugh** [comment]
To those reading closed issues, I received an email from @jaakkopoyry stating that his problems were due to password complexity issues.
