### ISSUE TITLE
Error Mounting Distribution Point

### ISSUE THREAD

**Issue by zachpw91** [jssimporter/JSSImporter#138]
I'm setting up JSS importer with Autopkgr for testing. I keep getting this error after setting up the JSS Importer config and then trying to run recipes. 

Error mounting url "smb://domainname;read/writeaccount:*******@distsharename.domainname:139/JAMF": None
Failed.

I checked the autopkg_results.plist and confirmed that the share name is right and the read/write password looks correct. Is there something I missed?

**Comment by sebtomasi** [comment]
The error is due to the port within the url, if you can get read of it it works, but you need to edit the builtin JSSImporter within "/Library/Application Support". So far I haven't found how to build the url without the port.
The workaround I found for running the recipes, it's to mount the repo before running autopkg.

**Comment by zachpw91** [comment]
What would I need to edit in /Library/Application Support?

Also, when you say mounting the repo, you mean mounting the share in finder and then running correct? Just wanted to clarify because I tried that and I'm getting the same error returned.

**Comment by sebtomasi** [comment]
In "/Library/Application Support/JSSImporter" there is a version of python-jss in JSS which is jss, so JSSImporter is using that version of python-jss.
The issue is that python-jss mount the JamfRepo that way smb://<user>:<password>@<hostname>:<port>/<ShareName>, if you try mounting that way the finder pops up this message
![screen shot 2018-06-14 at 07 48 49](https://user-images.githubusercontent.com/2770728/41393780-a56504ea-6fa7-11e8-99ee-9145c2465f73.png)

By removing the port in the url, it works

**Comment by zachpw91** [comment]
So how does one remove the port from the repo pathway? Is there something in the python scripts at /Library/Application Support/JSSImporter I need to edit? I dug through most of the directory, but could not find where the change needed to be made.

**Comment by sharrist** [comment]
I am getting the same error and would love to know the answer to that question.

**Comment by grahampugh** [comment]
@sharrist Is your smb mount using a non-standard port? 139 should work. Have you tried specifying the port in your Jamf Pro settings?

**Comment by sharrist** [comment]
No it's using the standard 139 port, I even changed the RW account password because it contained a "-" in it

**Comment by sharrist** [comment]
`Error mounting URL smb://DOMAIN;RWACCOUNT:RWACCOUNTPASSWORD@my.jss.server:139/caspershare": None` is the error I get in terminal

**Comment by sharrist** [comment]
And i get the screen saying The server will not allow any additional users to connect

**Comment by grahampugh** [comment]
Have you verified that the mount works when the port is omitted and fails when it is added? Nothing else is changed?

If so, I haven't tried this, so caveats all around. But, what happens if you remove the port entry from your Jamf Pro server? It has 139 filled in by default, so python-jss just grabs that information.

Otherwise, you can choose to explicitly supply your SMB configurations rather than get it from the Jamf Pro server. See https://github.com/jssimporter/python-jss/wiki/Configuration

**Comment by sharrist** [comment]
It's the port the screwing it up, weird though because my whole jss functions with 139 in the distribution point settings
