### ISSUE TITLE
AutoPkgr closes when setup JSSImporter

### ISSUE THREAD

**Issue by brianwarf** [jssimporter/JSSImporter#163]
Everytime I click on verify to complete the JSS setup inside JSS Importer, it crashes the app.  If I purposefully type a wrong password, it doesn't crash.  Thoughts?

**Comment by grahampugh** [comment]
@brianwarf What do you mean by "JSS setup inside JSS Importer"? Do you mean this:

`Everytime I click on verify to complete the JSSImporter setup inside AutoPkgr, it crashes the app`

If so, please raise the issue at AutoPkgr's GitHub: https://github.com/lindegroup/autopkgr/issues

Note, though, that AutoPkgr is not in very active development right now. I would recommend that you use the JSSImporter installer and setup instructions provided here rather than use the button within AutoPkgr.

**Comment by grahampugh** [comment]
Please try the latest version of AutoPkgr, 1.5.1, which has support for the latest version of JSSImporter.
