### ISSUE TITLE
Error with recipe, HTTPSConnectionPool

### ISSUE THREAD

**Issue by staze** [jssimporter/JSSImporter#168]
Not sure how to better diagnose what's going on, but seeing (changed text to exclude my JSS address):

HTTPSConnectionPool(host='jss.example.com', port=8443): Max retries exceeded with url: /JSSResource/distributionpoints (Caused by SSLError(SSLError(1, u'[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)'),))

Maybe this is because I'm running AutoPkgr/JSSImporter on 10.11.6, but curious what the heck is up. Everything LOOKS fine. This only seems to have broken recently.

**Comment by macmule** [comment]
@staze in short.. update the OS of the box running AutoPkg.. that error will be cipher or another SSL related thing due to the age of the OS. 

https://macmule.com/2015/12/31/10-8-x-clients-jss-9-73-api-sslv3-alert-handshake-failure/ << was a similar thing 4 years ago.

Again, update the OS on your AutoPkg host & should be good.

**Comment by staze** [comment]
bummer. I've got it running on an old xserve. lol. 

transfering to newer mac mini...

**Comment by staze** [comment]
that seems to have worked. Thanks! 

Guess these 2009 XServes have finally reached their end... lol.
