### ISSUE TITLE
Ability to upload to specific JSS's

### ISSUE THREAD

**Issue by dorminyk** [jssimporter/JSSImporter#178]
I'd like to see the ability to have more than 1 JSS entry....

for Example...

company1.jamfcloud.com
company2.jamfcloud.com
company3.jamfcloud.com

etc.

**Comment by grahampugh** [comment]
You could script that. I have over 30 Jamf instances and have a wrapper script to handle this. AutoPkg has the `--prefs` option so that is one way you can build around this, or you can script `defaults write` commands, but there is no ability to have multiple prefs in a single preference file. This will not be engineered directly into JSSImporter.
